"""GitHub repo creation, push, and pull request opening."""

import json
import os
import shutil
import subprocess
import tempfile
import threading
import urllib.error
import urllib.request
from pathlib import Path

from core.memory import update_project_memory
from integrations import n8n

BASE_DIR = Path(__file__).resolve().parent.parent
API_BASE = "https://api.github.com"


def push(slug: str) -> None:
    """Create a repo, push implementation/ to the ai-generated branch, open a PR.
    Runs in a background thread. Stores the PR URL in project_memory.json on success."""
    token = os.environ.get("GITHUB_TOKEN", "")
    username = os.environ.get("GITHUB_USERNAME", "")
    if not token or not username:
        return

    impl_dir = BASE_DIR / "output" / slug / "implementation"
    if not impl_dir.exists() or not any(impl_dir.iterdir()):
        return

    def _run():
        headers = {
            "Authorization": f"token {token}",
            "Content-Type": "application/json",
            "Accept": "application/vnd.github.v3+json",
        }

        def _gh(method, path, body=None):
            data = json.dumps(body).encode() if body else None
            req = urllib.request.Request(
                f"{API_BASE}{path}", data=data, headers=headers, method=method
            )
            try:
                resp = urllib.request.urlopen(req, timeout=15)
                return json.loads(resp.read())
            except urllib.error.HTTPError as e:
                return json.loads(e.read())

        repo = _gh("POST", "/user/repos", {
            "name": slug,
            "description": f"Generated by Pathless AI Office — {slug}",
            "private": False,
            "auto_init": True,
        })
        clone_url = repo.get("clone_url") or f"https://github.com/{username}/{slug}.git"
        auth_url = clone_url.replace("https://", f"https://{username}:{token}@")

        with tempfile.TemporaryDirectory() as tmpdir:
            r = subprocess.run(["git", "clone", auth_url, tmpdir],
                               capture_output=True, timeout=60)
            if r.returncode != 0:
                return

            for item in impl_dir.iterdir():
                dest = Path(tmpdir) / item.name
                if item.is_dir():
                    if dest.exists():
                        shutil.rmtree(dest)
                    shutil.copytree(item, dest)
                else:
                    shutil.copy2(item, dest)

            env = {**os.environ,
                   "GIT_AUTHOR_NAME": "AI Office",
                   "GIT_AUTHOR_EMAIL": "ai@pathless.ai",
                   "GIT_COMMITTER_NAME": "AI Office",
                   "GIT_COMMITTER_EMAIL": "ai@pathless.ai"}

            subprocess.run(["git", "checkout", "-b", "ai-generated"],
                           cwd=tmpdir, capture_output=True, env=env)
            subprocess.run(["git", "checkout", "ai-generated"],
                           cwd=tmpdir, capture_output=True, env=env)
            subprocess.run(["git", "add", "."],
                           cwd=tmpdir, capture_output=True, env=env)
            subprocess.run(["git", "commit", "-m",
                            f"feat: AI Office implementation for {slug}"],
                           cwd=tmpdir, capture_output=True, env=env)
            push_result = subprocess.run(["git", "push", auth_url, "ai-generated", "--force"],
                                         cwd=tmpdir, capture_output=True, timeout=120, env=env)
            if push_result.returncode != 0:
                return

        pr = _gh("POST", f"/repos/{username}/{slug}/pulls", {
            "title": f"AI Office: {slug} — initial implementation",
            "body": (
                f"## Generated by Pathless AI Office\n\n"
                f"**Project:** {slug}\n\n"
                "This PR contains the full implementation produced by the AI agent team:\n"
                "- **Bjorn** — system architecture\n"
                "- **Magnus** — GDPR/compliance\n"
                "- **Dag** — infrastructure & Docker\n"
                "- **Arve** — full-stack implementation\n\n"
                "_Review the output files in this branch for details._"
            ),
            "head": "ai-generated",
            "base": "main",
        })

        pr_url = pr.get("html_url")
        if not pr_url:
            existing = _gh("GET", f"/repos/{username}/{slug}/pulls?state=open&head={username}:ai-generated")
            if isinstance(existing, list) and existing:
                pr_url = existing[0].get("html_url")
        if not pr_url:
            return

        update_project_memory(slug, {
            "github_pr": pr_url,
            "github_repo": f"https://github.com/{username}/{slug}",
        })

        n8n.notify(slug, "system", "github-pr.md", f"GitHub PR opened: {pr_url}")

    threading.Thread(target=_run, daemon=True).start()
